# Generated by Django 5.1.2 on 2024-12-01 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_permisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoproducto',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios_permisos.carrito'),
        ),
    ]
