# Generated by Django 5.1.2 on 2024-10-30 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_permisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Finanzas',
                'db_table': 'Finanza',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios_permisos.caja')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios_permisos.carrito')),
                ('finanzas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios_permisos.finanzas')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
            },
        ),
    ]
