# Generated by Django 5.1.2 on 2024-11-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_permisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Contenido',
                'verbose_name_plural': 'Tipos de Contenido',
            },
        ),
    ]
