# Generated by Django 5.1.2 on 2024-11-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_permisos', '0002_tipodecontenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoDeContenido',
        ),
    ]
