# Generated by Django 5.1.1 on 2024-11-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_permisos', '0002_finanzas_venta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_Proveedor',
            new_name='precio_proveedor',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_Tienda',
            new_name='precio_tienda',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='ganancia_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ganancia_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ]
