# Generated by Django 5.1.2 on 2024-11-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_permisos', '0003_bitacora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bitacora',
        ),
    ]
