# Generated by Django 5.1.1 on 2024-11-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_permisos', '0003_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
    ]
