# Generated by Django 5.1.2 on 2024-11-19 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_permisos', '0005_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios_permisos.rol'),
        ),
    ]
