# Generated by Django 5.1.2 on 2024-11-23 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_permisos', '0006_alter_bitacora_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('purchase', 'Compra')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['usuario'], name='Bitacora_usuario_4a6c74_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['rol'], name='Bitacora_rol_id_c71f71_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['created_at'], name='Bitacora_created_63f16a_idx'),
        ),
    ]
