# Generated by Django 5.1.2 on 2024-11-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_permisos', '0007_alter_bitacora_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('purchase', 'Compra'), ('login', 'Inicio de Session'), ('logout', 'Cierre de Session')], max_length=50),
        ),
    ]
